name: eda
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=22.2.2
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - jinja2=3.0.3
  - pip:
    - wandb == 0.13.2
